epoch: 20
n_grad_acc: 1

# pe_present only model
model:
  class: ImgModelPE
  param:
    archi: efficientnet_b0

criterion:
  class: ImgLossPE
  param: {}

optimizer:
  class: Adam
  param:
    lr: 0.0005  # ImgLossPE is 2x bigger, so use 2x small lr

dataset:
  class: RsnaDataset
  param:
    oversample: 3
# use this: 
# def get_transform_v2_512():
#     return alb.Compose([
#         alb.RandomCrop(448, 448, p=1),
#         # alb.HorizontalFlip(p=0.5),
#         alb.VerticalFlip(p=0.5),
#     ])

dataloader_train:
  param:
    batch_size: 32  #56
    num_workers: 4
dataloader_valid:
  param:
    batch_size: 36  #96
    num_workers: 4

# do not change LR
scheduler:
  class: StepLR
  param:
    step_size: 9999
