# 最終学習. lossだけ少し変える: centralの重みを1/2=>1/4へ
epoch: 1
n_grad_acc: 1

model:
  class: ImgModelPE
  param:
    archi: efficientnet_b0

criterion:
  class: ImgLossPE2
  param: {}

optimizer:
  class: Adam
  param:
    lr: 0.0005  # ImgLossPE is 2x bigger, so use 2x small lr

dataset:
  class: RsnaDataset
  param:
    oversample: null
    posexam_only: true
    train_transform_str: get_transform_v4_512

dataloader_train:
  param:
    batch_size: 32  #56
    num_workers: 4
dataloader_valid:
  param:
    batch_size: 36  #96
    num_workers: 4

# do not change LR
scheduler:
  class: StepLR
  param:
    step_size: 9999
