epoch: 15
n_grad_acc: 1

model:
  class: ImgModelChronic
  param:
    archi: efficientnet_b0

criterion:
  class: ImgLossChronic
  param: {}

dataset:
  class: RsnaDataset
  param: {}

dataloader_train:
  param:
    batch_size: 56
    num_workers: 4
dataloader_valid:
  param:
    batch_size: 96
    num_workers: 4

scheduler:
  class: ReduceLROnPlateau
  param:
    factor: 0.5
    patience: 1
    verbose: True

