epoch: 20
n_grad_acc: 1

# pe_present only model
model:
  class: ImgModel
  param:
    archi: efficientnet_b0

criterion:
  class: ImgLoss
  param: {}

dataset:
  class: RsnaDataset
  param: {}

dataloader_train:
  param:
    batch_size: 56
    num_workers: 4
dataloader_valid:
  param:
    batch_size: 96
    num_workers: 4

# do not change LR
scheduler:
  class: StepLR
  param:
    step_size: 9999
