epoch: 15
n_grad_acc: 1

model:
  class: ImgModelRL
  param:
    archi: efficientnet_b0

criterion:
  class: ImgLossRL
  param: {}

optimizer:
  class: Adam
  param:
    lr: 0.001

dataset:
  class: RsnaDataset
  param: {}

dataloader_train:
  param:
    batch_size: 32
    num_workers: 4
dataloader_valid:
  param:
    batch_size: 36
    num_workers: 4

scheduler:
  class: StepLR
  param:
    step_size: 9999

